---
title: Humanity Torbay
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: admin@humanitytorbay.org.uk/
description: 'Making a difference to people''s lives.

'
baseurl: 
lang: en
url: http://humanitytorbay.org.uk/
twitter_username: humanitytorbay
facebook_username: humanitytorbay
markdown: kramdown
relative_permalinks: false
permalink: "/:categories/:title/"
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"
compress_html:
  comments:
  - "<!-- "
  - " -->"
  clippings: all
  endings: all
sass:
  sass_dir: assets/_sass
  style: compressed
plugins:
- jekyll-maps
- jekyll-admin
- jekyll-twitter-plugin
images: "/assets/images"
maps:
  google:
    api_key: AIzaSyCocy6_kZ4oaS0t1nrOMYsEZkbr6YcZPrU
